version: '3.8'
services:
    db:
      image: postgres:14.2
      restart: always
      environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
      ports:
        - '5432:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
        # copy the sql script to create tables
        - ./app/sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
        # copy the sql script to populate tables
        - ./app/sql/populate_table.sql:/docker-entrypoint-initdb.d/populate_table.sql
    test:
      build: .
      environment:
        - DB_HOST=db
        - DB_NAME=postgres
        - DB_USER=postgres
        - DB_PASSWORD=postgres
        - DB_PORT=5432
      command: bash -c "pytest -v -s app/test"
      depends_on:
        - db