version: '3.8'
services:
    postgres:
      image: postgres:14.2
      restart: always
      environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
        # copy the sql script to create tables
        - ./app/sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
        # copy the sql script to populate tables
        - ./app/sql/populate_table.sql:/docker-entrypoint-initdb.d/populate_table.sql
